<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

//account anderson_business
use LDAP\Result;

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/oauth2/token');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
curl_setopt($ch, CURLOPT_USERPWD, "AUGmAdOyjusVsx_rh4vhf0P-zaAE1S2HpFH9u9F8SMfQNS6EFDrG9C5mkL7gfgCyTbgeSf621VRgZRSe".":"."ENzUImC0YGNnnyrFCoVpDM3RP6EhzpV818OD5JqYnGfu6blot8dyEbrwDZNZ1sqzKixGxb05es--XiSl");

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

//Converter todo o retorno em somente Acess Token
$result = json_decode($result);
//$result = $result->access_token;


if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$atoken = $result->access_token;
return $result->access_token;

?>