<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
session_start();

$access_token = require("./aTokenCreate.php");

$_SESSION['access_token'] = $access_token;
$pp_Request_id = 'PRODUCT'. uniqid();
$_SESSION['pp_Request_id'] = $pp_Request_id;
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{
    \n  
    \"name\": \"Video Streaming Service\",
    \n  
    \"description\": \"A video streaming service\",
    \n  \"type\": \"SERVICE\",
    \n  \"category\": \"SOFTWARE\",
    \n  \"image_url\": \"https://example.com/streaming.jpg\",
    \n  \"home_url\": \"https://example.com/home\"
    \n}");
    
    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '. $access_token;
    $headers[] = 'Paypal-Request-Id:'. $pp_Request_id;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $result = json_decode($result);
//print_r($result);


    $_SESSION['product_id'] = $result->id;
    
    ?>