<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
require('./create_Product.php');
$ch = curl_init();
$access_token = $_SESSION['access_token'];
$product_id = $_SESSION['product_id'];
$pp_Request_id = $_SESSION['pp_Request_id'];


curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing/plans');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{
    \n      \"product_id\": \"$product_id\",
    \n      \"name\": \"Basic Plan\",
    \n      \"description\": \"Basic plan\",
    \n      \"billing_cycles\": [
        \n        {
            \n          \"frequency\": {
                \n            \"interval_unit\": \"MONTH\",
                \n            \"interval_count\": 1
                \n          },
                \n          \"tenure_type\": \"TRIAL\",
                \n          \"sequence\": 1,
                \n          \"total_cycles\": 1
                \n        },
                \n        {
                    \n          \"frequency\": {
                        \n            \"interval_unit\": \"MONTH\",
                        \n            \"interval_count\": 1
                        \n          },
                        \n          \"tenure_type\": \"REGULAR\",
                        \n          \"sequence\": 2,
                        \n          \"total_cycles\": 12,
                        \n          \"pricing_scheme\": {
                            \n            \"fixed_price\": {
                                \n              \"value\": \"10\",
                                \n              \"currency_code\": \"BRL\"
                                \n            }
                                \n          }
                                \n        }
                                \n      ],
                                \n      \"payment_preferences\": {
                                    \n        \"auto_bill_outstanding\": true,
                                    \n        \"setup_fee\": {
                                        \n          \"value\": \"10\",
                                        \n          \"currency_code\": \"BRL\"
                                        \n        },
                                        \n        \"setup_fee_failure_action\": \"CONTINUE\",
                                        \n        \"payment_failure_threshold\": 3
                                        \n      },
                                        \n      \"taxes\": {
                                            \n        \"percentage\": \"10\",
                                            \n        \"inclusive\": false
                                            \n      }
                                            \n    
                                        }");


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '. $access_token;
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Paypal-Request-Id: '. $pp_Request_id;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    $result = json_decode($result);
    print_r($result);
    $id_plan = $result->id;
    //echo(gettype($id_plan)); //string
    return $id_plan;
    
    ?>
    